name: continious-integration-learning
on:
  push:
    branches:
      -  main
      

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name : google formatter check 
      run : mvn com.spotify.fmt:fmt-maven-plugin:check

    - name : Gitleaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=.
